version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    container_name: web
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db